###### RANKED ### RANKED ### RANKED ### RANKED ### RANKED ### RANKED ### RANKED #####
#                                                                                   #
#   This is the config file for RANKED difficulty calculation                       #
#   This means that certain patterns though are difficult (extremely fast zigzags)  # 
#   don't boost the difficulty as we want to discourage those types of maps         #                          
#                                                                                   #
#####################################################################################

# Normal Sized Map Threshold
NormalSizedMapThreshold: 91 # Screw you TV-sized maps :)

# Density 
DensityTopProportion: 0.3
DensityTopWeighting: 1
DensityBottomWeighting: 0.3

DensitySingleStreamNPSCap: 8


# Tolerances
PatternToleranceMs: 20
SegmentToleranceMs: 10

# Overall weighting of pattern difficulties in GetPatternWeighting
GetPatternWeightingTopPercentage: 0.4
GetPatternWeightingTopWeight: 0.9
GetPatternWeightingBottomWeight: 0.1

# Density Average
SampleWindowSecs: 1 # Default 1 DO NOT CHANGE THIS LOL Since NPS calculations will be messed up
MovingAvgWindow: 5 # Default 5

# Interval NPS Thresholds
ShortIntervalNps: 5 # Default 5
MedIntervalNps: 1 # Default 1
LongIntervalNps: 0.5 # Default 0.5

#### Pattern Class Attributes
DefaultVariationWeighting: 0.5
DefaultPatternWeighting: 0.5
ShortIntDebuff: 0.7
MedIntDebuff: 0.6
LongIntDebuff: 0.4
ExtraIntEndDebuff: 0.9 # For if the interval is at the start or end

#### Strategies
# OtherCalcPatternMultiplier
OtherSwitchMultiplier: 1
OtherShortIntMultiplier: 0.8
OtherMedIntMultiplier: 0.7
OtherLongIntMultiplier: 0.5

#### Defined Pattern Multipliers
# NothingButTheory
NothingButTheoryLowBound: 1
NothingButTheoryUpBound: 1.5
NothingButTheoryLowClamp: 2.5
NothingButTheoryUpClamp: 21.5

# VaryingStreams
VaryingStreamsLowBound: 1
VaryingStreamsUpBound: 2
VaryingStreamsLowClamp: 2.5
VaryingStreamsUpClamp: 20.5

# ZigZagMultiplier
ZigZagLowBound: 1
ZigZagUpBound: 2
ZigZagLowClamp: 6
ZigZagUpClamp: 18

# EvenCircleMultiplier
EvenCircleLowBound: 1
EvenCircleUpBound: 1.55

# SkewedCircleMultiplier
SkewedCircleLowBound: 1
SkewedCircleUpBound: 1.75

# StreamMultiplier
StreamLowBound: 1
StreamUpBound: 1.3
StreamLowClamp: 5
StreamUpClamp: 14

# PatternStreamLengthMultiplier
PatternStreamLengthLowBound: 1.025
PatternStreamLengthUpBound: 1.1
PatternStreamLengthLowClamp: 6.5
PatternStreamLengthUpClamp: 20

# ZigZagLengthMultiplier
ZigZagLengthLowBound: 1
ZigZagLengthUpBound: 15
ZigZagLengthLowClamp: 15
ZigZagLengthUpClamp: 50
ZigZagLengthNpsThreshold: 17 # Slightly faster than EWF

# FourStackMultiplier
FourStackLowBound: 1.0
FourStackUpBound: 1.3
FourStackLowClamp: 5
FourStackUpClamp: 14

# ThreeStackMultiplier
ThreeStackLowBound: 1.0
ThreeStackUpBound: 1.2
ThreeStackLowClamp: 5
ThreeStackUpClamp: 14

# TwoStackMultiplier
TwoStackLowBound: 1.0
TwoStackUpBound: 1.15
TwoStackLowClamp: 5
TwoStackUpClamp: 14

# VaryingStacksMultiplier
VaryingStacksLowBound: 1.0
VaryingStacksUpBound: 1.35
VaryingStacksLowClamp: 4
VaryingStacksUpClamp: 14
