###### UNRANKED ### UNRANKED ### UNRANKED ### UNRANKED ### UNRANKED ### UNRANKED ####
#                                                                                   #
#   This is the config file for UNRANKED difficulty calculation                     #
#   This means that there is a less harsh cap on ZIG ZAGS and SINGLE LANE STREAMS   # 
#                                                                                   #
#####################################################################################

# Note that some of these aren't used and the ranked config is used (e.g., sample window threshold etc.)

# Normal Sized Map Threshold
NormalSizedMapThreshold: 0

# Density 
HardestSeconds: 15
Arbitrary90PercentThreshold: 1000
RankedPenaltyProportion: 0
CeilingProportion: 0.2

DensitySingleStreamNPSCap: 13
DensityFourStackNPSCap: 14
DensityThreeStackNPSCap: 15
DensityTwoStackNPSCap: 16

# Tolerances
PatternToleranceMs: 20
SegmentToleranceMs: 10

# Overall weighting of pattern difficulties in GetPatternWeighting
GetPatternWeightingTopPercentage: 0.4
GetPatternWeightingTopWeight: 0.9
GetPatternWeightingBottomWeight: 0.1

# Density Average
SampleWindowSecs: 1 # Default 1 DO NOT CHANGE THIS LOL Since NPS calculations will be messed up
MovingAvgWindow: 5 # Default 5

# Interval NPS Thresholds
ShortIntervalNps: 5 # Default 5
MedIntervalNps: 1 # Default 1
LongIntervalNps: 0.5 # Default 0.5

#### Pattern Class Attributes
DefaultVariationWeighting: 0.2
DefaultPatternWeighting: 0.8
ShortIntDebuff: 0.7
MedIntDebuff: 0.6
LongIntDebuff: 0.4
ExtraIntEndDebuff: 0.9 # For if the interval is at the start or end

#### Strategies
# OtherCalcPatternMultiplier
OtherSwitchMultiplier: 1
OtherShortIntMultiplier: 0.8
OtherMedIntMultiplier: 0.7
OtherLongIntMultiplier: 0.5

#### Defined Pattern Multipliers
# NothingButTheory
NothingButTheoryLowBound: 1
NothingButTheoryUpBound: 1.5
NothingButTheoryLowClamp: 2.5
NothingButTheoryUpClamp: 21.5

# ZigZagMultiplier
ZigZagLowBound: 1
ZigZagUpBound: 2
ZigZagLowClamp: 6
ZigZagUpClamp: 18

# EvenCircleMultiplier
EvenCircleLowBound: 1
EvenCircleUpBound: 1.15

# SkewedCircleMultiplier
SkewedCircleLowBound: 1
SkewedCircleUpBound: 1.25

# StreamMultiplier
StreamLowBound: 1
StreamUpBound: 1.5
StreamLowClamp: 5
StreamUpClamp: 14

# ZigZagLengthMultiplier
ZigZagLengthLowBound: 1
ZigZagLengthUpBound: 2
ZigZagLengthLowClamp: 15
ZigZagLengthUpClamp: 50
ZigZagLengthNpsThreshold: 17 # Slightly faster than EWF

# FourStackMultiplier
FourStackLowBound: 1.0
FourStackUpBound: 1.45
FourStackLowClamp: 5
FourStackUpClamp: 14

# ThreeStackMultiplier
ThreeStackLowBound: 1.0
ThreeStackUpBound: 1.35
ThreeStackLowClamp: 5
ThreeStackUpClamp: 14

# TwoStackMultiplier
TwoStackLowBound: 1.0
TwoStackUpBound: 1.3
TwoStackLowClamp: 5
TwoStackUpClamp: 14

# VaryingStacksMultiplier
VaryingStackMultiplier: 1.25

